import json
import re
import html
import requests
import time
import logging

logger = logging.getLogger(__name__)

_HEADERS = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                  "AppleWebKit/537.36 (KHTML, like Gecko) "
                  "Chrome/131.0.0.0 Safari/537.36",
    "Accept-Language": "ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7",
}


def fetch_transcript(video_id: str, lang: str = "ko") -> str | None:
    """YouTube 영상 자막 텍스트 가져오기 (3단계 폴백)"""

    # 방법 1: youtube-transcript-api (가장 안정적)
    text = _fetch_via_yt_api(video_id, lang)
    if text:
        return text

    # 방법 2: requests 직접 요청 (IP 차단 없을 때)
    text = _fetch_via_requests(video_id, lang)
    if text:
        return text

    # 방법 3: Google Apps Script 프록시
    text = _fetch_via_proxy(video_id, lang)
    if text:
        return text

    return None


def _fetch_via_yt_api(video_id: str, lang: str = "ko") -> str | None:
    """youtube-transcript-api 패키지로 자막 가져오기"""
    try:
        from youtube_transcript_api import YouTubeTranscriptApi

        ytt = YouTubeTranscriptApi()
        transcript = ytt.fetch(video_id, languages=[lang, "ko", "en"])
        texts = [snippet.text.strip() for snippet in transcript if snippet.text.strip()]
        if texts:
            result = " ".join(texts)
            logger.info(f"[yt-api] 자막 가져오기 성공: {video_id} ({len(result)}자)")
            return result
        return None
    except Exception as e:
        logger.debug(f"[yt-api] 실패: {video_id} - {e}")
        return None


def _fetch_via_proxy(video_id: str, lang: str = "ko") -> str | None:
    """Google Apps Script 프록시를 통해 자막 가져오기"""
    try:
        from app.config import get_settings
        proxy_url = get_settings().get_validated_proxy_url()
        if not proxy_url:
            return None

        resp = requests.get(
            proxy_url,
            params={"v": video_id, "lang": lang},
            timeout=10,
        )
        if resp.status_code != 200:
            return None

        data = resp.json()
        transcript = data.get("transcript", "")
        if transcript and len(transcript) > 10:
            logger.info(f"[proxy] 자막 가져오기 성공: {video_id} ({len(transcript)}자)")
            return transcript
        return None
    except Exception as e:
        logger.debug(f"[proxy] 실패: {video_id} - {e}")
        return None


def _fetch_via_requests(video_id: str, lang: str = "ko") -> str | None:
    """requests 세션으로 자막 XML 직접 가져오기"""
    try:
        session = requests.Session()
        session.headers.update(_HEADERS)

        resp = session.get(
            f"https://www.youtube.com/watch?v={video_id}", timeout=15
        )
        if resp.status_code != 200:
            return None

        match = re.search(r'"captionTracks":\s*(\[.*?\])', resp.text)
        if not match:
            return None

        try:
            tracks = json.loads(match.group(1))
        except json.JSONDecodeError:
            logger.debug(f"[requests] captionTracks JSON 파싱 실패: {video_id}")
            return None
        parsed = _parse_tracks(tracks)
        url = _pick_subtitle_url(parsed, lang)
        if not url:
            return None

        time.sleep(0.3)
        sub_resp = session.get(url, timeout=10)
        if sub_resp.status_code != 200:
            return None

        result = _parse_subtitle_xml(sub_resp.text)
        if result:
            logger.info(f"[requests] 자막 가져오기 성공: {video_id} ({len(result)}자)")
        return result
    except Exception:
        return None


def fetch_caption_tracks(video_id: str) -> list[dict]:
    """YouTube 영상 페이지에서 자막 트랙 목록만 추출"""
    try:
        resp = requests.get(
            f"https://www.youtube.com/watch?v={video_id}",
            headers=_HEADERS,
            timeout=15,
        )
        if resp.status_code != 200:
            return []

        match = re.search(r'"captionTracks":\s*(\[.*?\])', resp.text)
        if not match:
            return []

        try:
            return _parse_tracks(json.loads(match.group(1)))
        except json.JSONDecodeError:
            return []
    except Exception:
        return []


def _parse_tracks(tracks: list[dict]) -> list[dict]:
    result = []
    for track in tracks:
        name = track.get("name", {}).get("simpleText", "")
        result.append({
            "languageCode": track.get("languageCode", ""),
            "name": name,
            "baseUrl": track.get("baseUrl", ""),
            "isAutoGenerated": "자동" in name or "auto" in name.lower(),
        })
    return result


def _pick_subtitle_url(tracks: list[dict], preferred_lang: str) -> str | None:
    manual = [t for t in tracks if not t["isAutoGenerated"]]
    auto = [t for t in tracks if t["isAutoGenerated"]]

    for lang_code in [preferred_lang, "ko", "en"]:
        for track in manual:
            if track["languageCode"] == lang_code:
                return track["baseUrl"]
        for track in auto:
            if track["languageCode"] == lang_code:
                return track["baseUrl"]

    if manual:
        return manual[0]["baseUrl"]
    if auto:
        return auto[0]["baseUrl"]
    return None


def _parse_subtitle_xml(xml_text: str) -> str | None:
    texts = re.findall(r'<text[^>]*>(.*?)</text>', xml_text, re.DOTALL)
    if not texts:
        return None

    cleaned = []
    for t in texts:
        text = html.unescape(t)
        text = re.sub(r'<[^>]+>', '', text).strip()
        if text:
            cleaned.append(text)

    return " ".join(cleaned) if cleaned else None
