from collections import OrderedDict
from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.db.models import User
from app.api.shared import get_current_user
from app.transcript.transcript_fetcher import fetch_transcript, fetch_caption_tracks

router = APIRouter()

# 수동 자막 저장소 (메모리 캐시, 최대 500개, FIFO)
_manual_transcripts: OrderedDict[str, str] = OrderedDict()
_MAX_TRANSCRIPTS = 500
_MAX_TRANSCRIPT_LENGTH = 100_000


class TranscriptSubmit(BaseModel):
    transcript: str


@router.get("/video/{video_id}/transcript")
def get_transcript(
    video_id: str,
    lang: str = Query("ko", description="자막 언어 코드"),
    current_user: User = Depends(get_current_user),
):
    """영상 자막을 온디맨드로 가져오기"""
    # 수동 입력된 자막이 있으면 우선 반환
    if video_id in _manual_transcripts:
        return {
            "video_id": video_id,
            "lang": lang,
            "transcript": _manual_transcripts[video_id],
        }

    text = fetch_transcript(video_id, lang=lang)
    if text:
        return {
            "video_id": video_id,
            "lang": lang,
            "transcript": text,
        }

    # 자막 텍스트 실패 → 트랙 정보만 반환
    tracks = fetch_caption_tracks(video_id)
    return {
        "video_id": video_id,
        "lang": lang,
        "transcript": None,
        "tracks": [
            {"languageCode": t["languageCode"], "name": t["name"], "isAutoGenerated": t["isAutoGenerated"]}
            for t in tracks
        ] if tracks else [],
    }


@router.post("/video/{video_id}/transcript")
def submit_transcript(video_id: str, body: TranscriptSubmit, current_user: User = Depends(get_current_user)):
    """수동으로 자막 텍스트 제출"""
    text = body.transcript.strip()
    if not text:
        return {"ok": False, "error": "빈 자막"}
    if len(text) > _MAX_TRANSCRIPT_LENGTH:
        raise HTTPException(status_code=400, detail="자막이 너무 깁니다 (최대 10만자)")
    # 오래된 항목 제거 (FIFO, O(1))
    while len(_manual_transcripts) >= _MAX_TRANSCRIPTS:
        _manual_transcripts.popitem(last=False)
    _manual_transcripts[video_id] = text
    return {"ok": True, "video_id": video_id, "length": len(text)}
